name: .NET Core Desktop Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: TiendaPersonalizada.sln       # Nombre de la solución

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Restore Dependencies
      run: dotnet restore ${{ env.Solution_Name }}

    - name: Build Solution
      run: dotnet build ${{ env.Solution_Name }} -c ${{ matrix.configuration }}

    - name: Package Build Output
      run: |
        $outputPath = "package/TiendaPersonalizada-${{ matrix.configuration }}.zip"
        mkdir -p package
        Compress-Archive -Path **/bin/${{ matrix.configuration }}/* -DestinationPath $outputPath

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Build Package
        path: package/TiendaPersonalizada-${{ matrix.configuration }}.zip
