name: Build and Publish .NET App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-publish:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore Dependencies
      run: dotnet restore TiendaPersonalizada.sln

    - name: Build Solution
      run: dotnet build TiendaPersonalizada.sln -c Release

    - name: Publish Application
      run: |
        dotnet publish TiendaPersonalizada.sln -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -o publish
        mkdir -p package
        Compress-Archive -Path publish/* -DestinationPath package/TiendaPersonalizada.zip

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Build Package
        path: package/TiendaPersonalizada.zip
